spring:
    application:
        name: telecom-exchange-api
    datasource:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/exchange
        username: exchangeapp
        password: 4288
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
        show-sql: true
        hibernate:
            ddl-auto: none

server:
    port: 8181
    servlet:
      context-path: /api